### PR TITLE
Split driver and rider flow

### PR DESCRIPTION
**Pull request by benripka**
Split the driver and rider login. I also made it remember if you are logged in. Now when you login it launches either the DriverDashboardActivity or the RiderActivity, according to your type.

Both these activities are subclasses of an abstract Driver activity.

**** Note that the driver navigation drawers do not work yet, they will crash the app ****

But its just a matter of setting up the navigation for that

### CODE REVIEW

**Comment by stephenta** [comment]
I pulled the branch and did some testing. When I click the sign in button, it directs me to the sign in page then right back to the first activity. Then when I click sign in again, it crashes.. I tried both on the emulator and my phone.

Maybe someone else can test as well

**Comment by benripka** [comment]
Which member are you login it with?

**Comment by stephenta** [comment]
> Which member are you login it with?

**Comment by stephenta** [comment]
Whoops sorry closed it by accident lol.

What do you mean by member? Like I wasn't able to type anything into the login screen

**Comment by benripka** [comment]
Oooh I see ! It skips over the login page probably because you already have (from yesterday maybe) a user signed in. Can you try delete the app completely off your phone (this clears the authentication cache for your device) then try run and signin again? Maybe try the user:

jim@gmail.com
12341234
or
driver1@gmail.com
12341234

**Comment by benripka** [comment]
If it is the case that the member you were using is a bit old (does not have the boolean driver), it would crash the app looking for that.

**Comment by stephenta** [comment]
Okay currently testing it again

**Comment by stephenta** [comment]
Okay works for me now! Thanks for the quick trouble shooting

**Pull request merged**
